#+TITLE: Index2
#+AUTHOR: Markus Hoffmann

:REVEAL_PROPERTIES:
# #+REVEAL_ROOT: file:///home/flowmis/pres/reveal
#+REVEAL_ROOT: https://cdn.jsdelivr.net/npm/reveal.js
#+REVEAL_THEME: serif
#+REVEAL_INIT_OPTIONS: height:900, width:1600
# #+REVEAL_INIT_OPTIONS: minScale:0.5, maxScale:0.9, margin:0.9
#+OPTIONS: timestamp:t toc:nil num:nil reveal_title_slide:nil
:END:

* Info
- das hier soll der Passwortgesicherte Bereich sein dem ich niemand schicke (kommen nur durch Glück hier hin indem sie aus dem Link index.html zu index2.html machen)
- index.html ist der Passwortgesicherte Bereich den ich anderen schicken kann
- Passwortsicherung ist nur kleine Hürde, da Inhalt theoretisch durch mein öffentlichen github Account einsehbar ist, aber wenn dieser nicht bekannt ist und man nur den Link hat kann man nicht ohne Passwort oder direkt Link zugreifen - etwas Sicherheit bringt es also mit sich!
- Wie funktioniert die Passwortsicherung:
  - index.html in /root der repo hat eine form zum ausfüllen mit Passwörtern
  - von dem jeweils eingegebenen Passwort wird ein hash SHA1 gebildet und gecheckt ob dieser mit dem Ordner im /root Verzeichnis übereinstimmt
  - ist dem der Fall erfolgt die Weiterleitung zu der index.html in diesem Ordner der nach dem Hash des Passworts benannt ist
  - zum ändern des Passworts einfach das neue Passwort in die index.html im /root Ordner eingeben (muss halt rendern - kann ich durch github pages machen oder auch anders) -> dann kommt nach der Eingabe dass das Passwort falsch war und in der Adressleiste steht der Hash des eingegebenen Passworts -> diesen hinter dem # Zeichen kopieren und den Ordner nach dem Hash umbenennen -> nun wurde das Passwort geändert und man kann mit dem neuen Passwort auf den Ordner zugreifen! -> Idee/Form kam von [[https://github.com/chrissy-dev/protected-github-pages][hier]]
* Präsentationen
- [[https://flowmis.github.io/pres/51c54bdc32e6d845892e84e31b71ae1f9e02bbcd/TestPres.html][Präsentation(Test)]]

** TODO [0%]
- [ ] Das hier soll die Übersichtsseite meiner Präsentationen werden von der aus ich leicht auf alle meine vorhandenen Präsentationen zugreifen können möchte
- [ ] alle .html Dateien müssen noch automatisch in diese hier mit link geladen werden dass ich es nicht manuell adden muss
- [ ] Im Moment ist es selbst als Präsentation gestaltet, aber eigentlich macht es denke ich mehr Sinn anderes Web-Layout wie read-the-org darüber zu legen
- [ ] Am Ende sollen die Links zu den Präsentationen auf erster Seite direkt und am besten automatisch zu sehen sein!
* Links zu sontigen Projekten etc.
- [[https://flowmis.github.io/pres/51c54bdc32e6d845892e84e31b71ae1f9e02bbcd/Lesezeichen.html][Lesezeichen]]
- [[https://flowmis.github.io/pres/51c54bdc32e6d845892e84e31b71ae1f9e02bbcd/Event04082022][Event04082022]]
